export enum SESSION_STATUS_ENUM {
  LOCKED = 'locked',
  CURRENT = 'current',
  COMPLETED = 'completed',
}

export const SESSION_STATUS = {
  LOCKED: SESSION_STATUS_ENUM.LOCKED,
  CURRENT: SESSION_STATUS_ENUM.CURRENT,
  COMPLETED: SESSION_STATUS_ENUM.COMPLETED,
}; 