export enum MISSION_STATUS_ENUM {
  LOCKED = 'locked',
  CURRENT = 'current',
  COMPLETED = 'completed',
}

export const MISSION_STATUS = {
  LOCKED: MISSION_STATUS_ENUM.LOCKED,
  CURRENT: MISSION_STATUS_ENUM.CURRENT,
  COMPLETED: MISSION_STATUS_ENUM.COMPLETED,
};
